-
 name: Install Nginx
 hosts: div_servers
 become: yes

 tasks:
   - name: Install Nginx
     package:
       name: nginx
       state: latest
   - name: start nginx service
     systemd_service:
       name: nginx
       state: started
   - name: Enable service
     systemd_service:
       name: nginx
       enabled: true
